### ISSUE TITLE
cam_R_w2c and cam_t_w2c not in info.yml

### ISSUE THREAD

**Issue by kevinkit** [thodan/t-less_toolkit#1]
Great dataset, however the info.yml does not contain cam_R_w2c and cam_t_w2c  like stated in the t-less_doc.md - are they missing or where they moved somewhere else?

**Comment by thodan** [comment]
Hey Kevin. cam_R_w2c and cam_t_w2c are provided only for test images. I have added this info to t-less_doc.md. For training images, you can use cam_R_m2c and cam_t_m2c provided in gt.yml, which gives a transformation from the object model coordinate system to the camera coordinate system. There is nothing else than a single object in the training images, so you might want to assume that the model coordinate system and the world coordinate system coincide for the training images.
