### ISSUE TITLE
Updates and Bug Fixes

### ISSUE THREAD

**Issue by Clemens-Honold** [thodan/t-less_toolkit#11]
Hello,

First, I would like to express my appreciation for creating the t-less_toolkit. The concept behind it is excellent, and I urgently need to use it for testing and rendering poses.

However, I have encountered several issues that seem to be due to the code being outdated. Here are the problems I've identified:

- np.floats Deprecation: The code currently uses np.floats, which appears to be deprecated. It seems they are now simply called float.
- Dataset File Format: The dataset available for download on the BOP website provides files in JSON format instead of the required YML      format. Additionally, the file names differ from those expected by the toolkit.

I kindly request your assistance in resolving these issues to ensure the toolkit functions correctly. Given your familiarity with the code, I believe these problems can be fixed relatively quickly and easily by you.

Thank you for your attention to this matter.

Best regards,

**Comment by thodan** [comment]
Hello, please consider switching to BOP toolkit (https://github.com/thodan/bop_toolkit) which is maintained and provides most of the functionality (including support of the T-LESS format distributed on the BOP website).
