### ISSUE TITLE
check_poses_train_imgs.py seems to be using a different format than the dataset

### ISSUE THREAD

**Issue by martinarroyo** [thodan/t-less_toolkit#4]
I am trying to run the `check_poses_train_imgs.py` as I want to modify the rendering process for some experiments. However, I am running into some issues. First, the paths seem to be wrong:

```python
model_path_mask = os.path.join(data_path, 'models_' + model_type, 'obj_{:02d}.ply')
obj_info_path_mask = os.path.join(data_path, 'train_{}', 'obj_{:02d}', 'obj_info.yml')
rgb_path_mask = os.path.join(data_path, 'train_{}', 'obj_{:02d}', 'rgb', '{:04d}.{}')
depth_path_mask = os.path.join(data_path, 'train_{}', 'obj_{:02d}', 'depth', '{:04d}.png')
rgb_ext = {'primesense': 'png', 'kinect': 'png', 'canon': 'jpg'}
obj_colors_path = os.path.join('data', 'obj_rgb.txt')
vis_rgb_path_mask = os.path.join(output_dir, 'obj_{:02d}_{}_{}_{:04d}_rgb.png')
vis_depth_path_mask = os.path.join(output_dir, 'obj_{:02d}_{}_{}_{:04d}_depth_diff.png')
```

The `obj_` prefix is still there, even though the dataset now uses a different format. It should be:
```python
model_path_mask = os.path.join(data_path, 'models_' + model_type, 'obj_{:02d}.ply')
obj_info_path_mask = os.path.join(data_path, 'train_{}', '{:02d}', 'info.yml')
obj_gt_path_mask = os.path.join(data_path, 'train_{}', '{:02d}', 'gt.yml')
rgb_path_mask = os.path.join(data_path, 'train_{}', '{:02d}', 'rgb', '{:04d}.{}')
depth_path_mask = os.path.join(data_path, 'train_{}', '{:02d}', 'depth', '{:04d}.png')
rgb_ext = {'primesense': 'png', 'kinect': 'png', 'canon': 'jpg'}
obj_colors_path = os.path.join('data', 'obj_rgb.txt')
vis_rgb_path_mask = os.path.join(output_dir, '{:02d}_{}_{}_{:04d}_rgb.png')
vis_depth_path_mask = os.path.join(output_dir, '{:02d}_{}_{}_{:04d}_depth_diff.png')
```

Something similar happens with the transformation parameters, some of them are not in the `info.yml` file, but rather in `gt.yml`. This is a quick workaround that I implemented:

```diff
-        info = yaml.load(f, Loader=yaml.CLoader)
-        for eid in info.keys():
-            info[eid]['cam_K'] = np.array(info[eid]['cam_K']).reshape((3, 3))
-            info[eid]['cam_R_m2c'] = np.array(info[eid]['cam_R_m2c']).reshape((3, 3))
-            info[eid]['cam_t_m2c'] = np.array(info[eid]['cam_t_m2c']).reshape((3, 1))
+        with open(path2, 'r') as f2:
+            info = yaml.load(f, Loader=yaml.Loader)
+            gt = yaml.load(f2, Loader=yaml.Loader)
+            for eid in info.keys():
+                info[eid]['cam_K'] = np.array(info[eid]['cam_K']).reshape((3, 3))
+                gt[eid] = gt[eid][0]
+                gt[eid]['cam_R_m2c'] = np.array(gt[eid]['cam_R_m2c']).reshape((3, 3))
+                gt[eid]['cam_t_m2c'] = np.array(gt[eid]['cam_t_m2c']).reshape((3, 1))
+                info[eid].update(gt[eid])
```
Another thing is that after fixing these issues and some other minor ones, this is the result I got:

![01_canon_cad_0100_rgb](https://user-images.githubusercontent.com/4853097/35481107-48f64dcc-041d-11e8-9bdb-29f0eb196ede.png)

Instead of the expected:

![0099](https://user-images.githubusercontent.com/4853097/35481114-69947e96-041d-11e8-8b20-deb459c05d30.jpg)
I got this by using the colors from the data/obj_rgb.txt file:

```diff
-        # surf_color = obj_colors[obj_id]
-        surf_color = (1, 0, 0)
+        surf_color = obj_colors[obj_id]
+        #surf_color = (1, 1, 1)
```

As such, I would like to ask if there is a newer version of these scripts to render the objects, or if I have to resort to an older version of the dataset, or if I am doing anything wrong altogether.

Thanks a lot for your help in advance!

**Comment by thodan** [comment]
Hi, thanks for pointing out the issues! I have fixed both _check_poses_test_imgs.py_ and _check_poses_train_imgs.py_.

Regarding the rendering, I cannot reproduce the weird outcome you are getting. I would recommend switching to the SIXD Toolkit (https://github.com/thodan/sixd_toolkit), which includes the functionality of the T-LESS Toolkit, but is more general and more tested.

**Comment by martinarroyo** [comment]
@thodan Thanks a lot!

**Comment by mengce97** [comment]
i got the same problem(laugh cry) when i run the check_poses_test_imgs.py 
![20_primesense_cad_0400_rgb](https://user-images.githubusercontent.com/48461453/54514583-81507800-4995-11e9-8614-695ac220a542.png)
some of them are right 
![01_primesense_cad_0000_rgb](https://user-images.githubusercontent.com/48461453/54514621-92998480-4995-11e9-9fb0-9996430cfa46.png)
why does this happen?
Thank u a lot !
