### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by heborras** [thodan/t-less_toolkit#5]
Hey,
I really like that in addition to the T-Less Dataset you supply tools to use and render this data. However since the code currently doesn’t include a license it is literally illegal to use this software, see this helpful [guide](https://choosealicense.com/no-permission/).
It would be great if you could add a license so that people don’t slip into a grey area when they use this code.
By the way: The same would of course be nice for the other repositories: sixd_toolkit and obj_pose_eval .

Cheers,
Hendrik

**Comment by thodan** [comment]
Hi Hendrik,

Thanks for your suggestion. I've added a LICENSE file to all three repositories (t-less_toolkit, sixd_toolkit, and obj_pose_eval).

Note that the T-LESS dataset stays under Creative Commons Attribution-ShareAlike 4.0 license, as mentioned on http://cmp.felk.cvut.cz/t-less.

Tomas
