### ISSUE TITLE
Is there mask for every object in the picture?

### ISSUE THREAD

**Issue by HuaWeitong** [thodan/t-less_toolkit#6]

**Comment by thodan** [comment]
The masks are not provided with the dataset. You can obtain them by projecting the 3D object models in the ground-truth poses. You can start with this script: https://github.com/thodan/sixd_toolkit/blob/master/tools/vis_gt_poses.py (the object mask is calculated at line 149).

**Comment by HuaWeitong** [comment]
> The masks are not provided with the dataset. You can obtain them by projecting the 3D object models in the ground-truth poses. You can start with this script: https://github.com/thodan/sixd_toolkit/blob/master/tools/vis_gt_poses.py (the object mask is calculated at line 149).

Thank you so much !
