### ISSUE TITLE
Some questions about training and test data

### ISSUE THREAD

**Issue by HuaWeitong** [thodan/t-less_toolkit#7]
Hi, I met some problems when training with T-less. The trained model does not perform well on the test data, I think maybe the training of individual parts in a black background does not work in a new chaotic background. Do you have some suggestions?

**Comment by thodan** [comment]
Hello, I suggest checking some recent papers on 6D object pose estimation to see how you can synthesize better training images, e.g.:
1) http://openaccess.thecvf.com/content_ICCV_2017/papers/Kehl_SSD-6D_Making_RGB-Based_ICCV_2017_paper.pdf
2) https://arxiv.org/pdf/1902.03334.pdf
